inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
